on: push
name: Build and Generate Android Apk
jobs:
  build:
    name: Build APK
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.1
      
      - name: Build the project
        run: msbuild Peedroca.Healthy\Peedroca.Healthy.sln /p:Configuration=Release;Platform="Any CPU" /t:Peedroca.Healthy
      
      - name: Sign the .apk file
        run: msbuild Peedroca.Healthy\Healthy.Mobile\Healthy.Mobile\Healthy.Mobile.csproj /p:Configuration=Release;Platform="Any CPU" /t:SignAndroidPackage
      
      - name: Zip-align and deploy the signed .apk file
        run: zipalign -f -v 4 "**/*.apk" "Demo.apk"
